export const DATA = [
  {content: 'A', blob: true, L: '15%', T: '35%'},
  {content: 'B', blob: false, L: '35%', T: '15%'},
  {content: 'C', blob: false, L: '25%', T: '5%'},
  {content: 'D', blob: true, L: '5%', T: '23'},
  {content: 'E', blob: false, L: '75%', T: '30%'},
  {content: 'F', blob: true, L: '56%', T: '35%'},
  {content: 'G', blob: false, L: '34%', T: '27%'},
  {content: 'H', blob: true, L: '55%', T: '11%'},
  {content: 'I', blob: false, L: '3%', T: '18%'},
  {content: 'J', blob: false, L: '44%', T: '9%'},
  {content: 'K', blob: true, L: '40%', T: '12%'},
  {content: 'L', blob: true, L: null, T: null},
  {content: 'M', blob: true, L: null, T: null},
  {content: 'N', blob: false, L: null, T: null},
  {content: 'O', blob: false, L: null, T: null},
  {content: 'P', blob: true, L: null, T: null},
  {content: 'Q', blob: true, L: null, T: null},
  {content: 'R', blob: false, L: null, T: null},
  {content: 'S', blob: true, L: null, T: null},
  {content: 'T', blob: true, L: null, T: null},
  {content: 'U', blob: false, L: null, T: null},
  {content: 'W', blob: true, L: null, T: null},
  {content: 'X', blob: true, L: null, T: null},
  {content: 'Y', blob: false, L: null, T: null},
  {content: 'Z', blob: true, L: null, T: null}
];
